/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import control.FuncoesUteis;
import control.GerenciadorInterface;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Endereco;
import model.Entregador;

/**
 *
 * @author phfde
 */
public class DlgCadEntregadores extends javax.swing.JDialog {

    /**
     * Creates new form DlgCadastroClientes
     */
    private Entregador entregador;

    public DlgCadEntregadores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        entregador = null;
                ImageIcon logoIcon = new ImageIcon("cadentregador.png");

        // Cria um JLabel para armazenar a imagem
        JLabel logoLabel = new JLabel(logoIcon);
        logoLabel.setHorizontalAlignment(JLabel.CENTER); // Centraliza a imagem

        // Se você quiser adicionar a imagem a um JPanel já existente no formulário (por exemplo, jPanelLogo)
        txtLogo.setLayout(new BorderLayout()); // Certifique-se de usar o layout correto
        txtLogo.add(logoLabel, BorderLayout.CENTER);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpEstadoCivil = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        rdbSolteiro1 = new javax.swing.JRadioButton();
        rdbCasado1 = new javax.swing.JRadioButton();
        rdbDivorciado = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        txtNome = new javax.swing.JLabel();
        cxtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JLabel();
        cxtCPF = new javax.swing.JFormattedTextField();
        txtData = new javax.swing.JLabel();
        cxtData = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        rdbSolteiro = new javax.swing.JRadioButton();
        rdbCasado = new javax.swing.JRadioButton();
        rdpDivorciado = new javax.swing.JRadioButton();
        txtCelular = new javax.swing.JLabel();
        cxtCelular = new javax.swing.JFormattedTextField();
        txtEstado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtCEP = new javax.swing.JLabel();
        cxtCEP = new javax.swing.JFormattedTextField();
        txtCidade = new javax.swing.JLabel();
        cxtCidade = new javax.swing.JTextField();
        txtBairro = new javax.swing.JLabel();
        cxtBairro = new javax.swing.JTextField();
        txtN = new javax.swing.JLabel();
        cxtN = new javax.swing.JTextField();
        txtRua = new javax.swing.JLabel();
        cxtRua = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtMarca = new javax.swing.JLabel();
        txtModelo = new javax.swing.JLabel();
        txtAno = new javax.swing.JLabel();
        txtTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        spnAno = new javax.swing.JSpinner();
        cxtModelo = new javax.swing.JTextField();
        cxtMarca = new javax.swing.JTextField();
        txtLogo = new javax.swing.JLabel();

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        rdbSolteiro1.setText("Solteiro(a)");
        rdbSolteiro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSolteiro1ActionPerformed(evt);
            }
        });
        jPanel6.add(rdbSolteiro1);

        rdbCasado1.setText("Casado(a)");
        jPanel6.add(rdbCasado1);

        rdbDivorciado.setText("Divorciado(a)");
        jPanel6.add(rdbDivorciado);

        setTitle("Cadastro de Entregadores");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        txtNome.setText("Nome");

        txtCPF.setText("CPF");

        try {
            cxtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cxtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxtCPFActionPerformed(evt);
            }
        });

        txtData.setText("Dt Nasc. ");

        try {
            cxtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        grpEstadoCivil.add(rdbSolteiro);
        rdbSolteiro.setText("Solteiro(a)");
        rdbSolteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSolteiroActionPerformed(evt);
            }
        });
        jPanel4.add(rdbSolteiro);

        grpEstadoCivil.add(rdbCasado);
        rdbCasado.setText("Casado(a)");
        jPanel4.add(rdbCasado);

        grpEstadoCivil.add(rdpDivorciado);
        rdpDivorciado.setText("Divorciado(a)");
        jPanel4.add(rdpDivorciado);

        txtCelular.setText("Celular");

        try {
            cxtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cxtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxtCelularActionPerformed(evt);
            }
        });

        txtEstado.setText("Estado Civil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtData)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCelular)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNome)
                                .addComponent(txtCPF)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cxtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                .addComponent(cxtData)
                                .addComponent(cxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEstado)
                        .addGap(74, 74, 74))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNome)
                        .addComponent(cxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEstado, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCPF)
                            .addComponent(cxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtData)
                            .addComponent(cxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelular)
                            .addComponent(cxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));
        jPanel2.setName("gdffdg"); // NOI18N

        txtCEP.setText("CEP");

        try {
            cxtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cxtCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxtCEPFocusLost(evt);
            }
        });

        txtCidade.setText("Cidade");

        txtBairro.setText("Bairro");

        txtN.setText("N°");

        txtRua.setText("Rua");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCEP)
                    .addComponent(txtBairro)
                    .addComponent(txtN))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCidade))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxtN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRua)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cxtCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(cxtRua))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCEP)
                    .addComponent(cxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade)
                    .addComponent(cxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro)
                    .addComponent(cxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRua)
                    .addComponent(cxtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtN)
                    .addComponent(cxtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/accept.png"))); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/remove.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btnConfirmar)
                .addGap(58, 58, 58)
                .addComponent(btnCancelar)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Veiculo"));
        jPanel5.setName("gfdgdf"); // NOI18N

        txtMarca.setText("Marca");

        txtModelo.setText("Modelo");

        txtAno.setText("Ano");

        txtTipo.setText("Tipo");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hatch", "Cedã", "Furgão" }));

        spnAno.setModel(new javax.swing.SpinnerListModel(new String[] {"2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024"}));
        spnAno.setName(""); // NOI18N

        cxtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxtModeloActionPerformed(evt);
            }
        });

        cxtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxtMarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAno))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(txtModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTipo)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnAno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAno)
                    .addComponent(spnAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarca)
                    .addComponent(cxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelo)
                    .addComponent(txtTipo)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        txtLogo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtLogo.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:

        if (validarCampos()) {
            String nome = cxtNome.getText();
            String cpf = cxtCPF.getText();
            String dtNasc = cxtData.getText();
            Date data = null;
            try {
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                LocalDate localDate = LocalDate.parse(dtNasc, formatter);
                data = Date.from(localDate.atStartOfDay(ZoneId.systemDefault()).toInstant());

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(this, "Data Inválida", "Erro Data", JOptionPane.ERROR_MESSAGE);
                return;
                
            }

            String cep = cxtCEP.getText();
            String cidade = cxtCidade.getText();
            String bairro = cxtBairro.getText();
            String logradouro = cxtRua.getText();
            String modelo = cxtModelo.getText();
            String marca = cxtMarca.getText();
            String tipo = (String) cmbTipo.getSelectedItem();
            String estadoCivil = null;
            String ano = spnAno.getValue().toString();
            int anoFabricacao = Integer.parseInt(ano);
            String num = cxtN.getText();
            int numero = Integer.parseInt(num);

            if (rdbSolteiro.isSelected()) {
                estadoCivil = "Solteiro";
            } else if (rdbCasado.isSelected()) {
                estadoCivil = "Casado";
            } else {
                estadoCivil = "Divorciado";
            }

            try {
                if (entregador == null) {
                    int id = GerenciadorInterface.getMyInstance().getGerDom().inserirEntregador(new Date(), modelo, marca,
                            anoFabricacao, tipo, nome, cpf, data, estadoCivil, cep, bairro, cidade,
                            logradouro, numero);
                            JOptionPane.showMessageDialog(this, "Entregador " + id + " inserido com sucesso.");

                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex, "ERRO Entregador", JOptionPane.ERROR_MESSAGE);

            }

        } else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos", "Erro no Cadastro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void cxtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxtCPFActionPerformed

    private void rdbSolteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSolteiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbSolteiroActionPerformed

    private void cxtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxtCelularActionPerformed

    private void cxtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxtModeloActionPerformed

    private void cxtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxtMarcaActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_formComponentShown

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cxtCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxtCEPFocusLost
        // TODO add your handling code here:

        try {
            String cep = cxtCEP.getText();

            Endereco ender = FuncoesUteis.consultarCEP(cep);
            if (ender != null) {
                cxtRua.setText(ender.getLogradouro());
                cxtBairro.setText(ender.getBairro());
                cxtCidade.setText(ender.getCidade());;
                //cmbCidade.setSelectedItem(ender.getCidade());
            } else {
                JOptionPane.showMessageDialog(this, "CEP não encontrado.", "Cadastro de Cliente", JOptionPane.ERROR_MESSAGE);
                cxtRua.setText("");
                cxtCidade.setText("");
                cxtBairro.setText("");
                //txtRef.setText("");
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex, "Cadastro de Cliente", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cxtCEPFocusLost
    private boolean validarCampos() {
        int invalidos = 0;
        txtNome.setForeground(Color.lightGray);
        txtData.setForeground(Color.lightGray);
        txtCPF.setForeground(Color.lightGray);
        txtCelular.setForeground(Color.lightGray);
        txtCEP.setForeground(Color.lightGray);
        txtBairro.setForeground(Color.lightGray);
        txtCidade.setForeground(Color.lightGray);
        txtRua.setForeground(Color.lightGray);
        txtN.setForeground(Color.lightGray);
        txtEstado.setForeground(Color.lightGray);
        txtMarca.setForeground(Color.lightGray);
        txtModelo.setForeground(Color.lightGray);

        if (cxtNome.getText().trim().isEmpty()) {
            invalidos++;
            txtNome.setForeground(Color.red);

        }
        if (cxtData.getValue() == null) {
            invalidos++;
            txtData.setForeground(Color.red);

        }
        if (cxtCelular.getValue() == null) {
            invalidos++;
            txtCelular.setForeground(Color.red);

        }
        if (cxtCPF.getValue() == null) {
            invalidos++;
            txtCPF.setForeground(Color.red);

        }
        if (cxtCEP.getValue() == null) {
            invalidos++;
            txtCEP.setForeground(Color.red);

        }
        if (cxtBairro.getText().isEmpty()) {
            invalidos++;
            txtBairro.setForeground(Color.red);

        }
        if (cxtN.getText().isEmpty()) {
            invalidos++;
            txtN.setForeground(Color.red);

        }
        if (cxtRua.getText().isEmpty()) {
            invalidos++;
            txtRua.setForeground(Color.red);

        }
        if (cxtCidade.getText().isEmpty()) {
            invalidos++;
            txtCidade.setForeground(Color.red);

        }
        if (grpEstadoCivil.isSelected(null)) {
            invalidos++;
            txtEstado.setForeground(Color.red);

        }
        if (cxtMarca.getText().isEmpty()) {
            invalidos++;
            txtMarca.setForeground(Color.red);

        }
        if (cxtModelo.getText().isEmpty()) {
            invalidos++;
            txtModelo.setForeground(Color.red);

        }
        if (invalidos == 0) {
            return true;
        } else {
            return false;
        }
    }
    private void rdbSolteiro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSolteiro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbSolteiro1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JTextField cxtBairro;
    private javax.swing.JFormattedTextField cxtCEP;
    private javax.swing.JFormattedTextField cxtCPF;
    private javax.swing.JFormattedTextField cxtCelular;
    private javax.swing.JTextField cxtCidade;
    private javax.swing.JFormattedTextField cxtData;
    private javax.swing.JTextField cxtMarca;
    private javax.swing.JTextField cxtModelo;
    private javax.swing.JTextField cxtN;
    private javax.swing.JTextField cxtNome;
    private javax.swing.JTextField cxtRua;
    private javax.swing.ButtonGroup grpEstadoCivil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton rdbCasado;
    private javax.swing.JRadioButton rdbCasado1;
    private javax.swing.JRadioButton rdbDivorciado;
    private javax.swing.JRadioButton rdbSolteiro;
    private javax.swing.JRadioButton rdbSolteiro1;
    private javax.swing.JRadioButton rdpDivorciado;
    private javax.swing.JSpinner spnAno;
    private javax.swing.JLabel txtAno;
    private javax.swing.JLabel txtBairro;
    private javax.swing.JLabel txtCEP;
    private javax.swing.JLabel txtCPF;
    private javax.swing.JLabel txtCelular;
    private javax.swing.JLabel txtCidade;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtEstado;
    private javax.swing.JLabel txtLogo;
    private javax.swing.JLabel txtMarca;
    private javax.swing.JLabel txtModelo;
    private javax.swing.JLabel txtN;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtRua;
    private javax.swing.JLabel txtTipo;
    // End of variables declaration//GEN-END:variables
}
