/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.GerenciadorInterface;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author phfde
 */
public class FrmPrincipal extends javax.swing.JFrame {

    public FrmPrincipal() {
        initComponents();  // Inicializa os componentes gerados pela ferramenta de design

        // Carrega a imagem do logo
        ImageIcon logoIcon = new ImageIcon("img3.png");

        // Cria um JLabel para armazenar a imagem
        JLabel logoLabel = new JLabel(logoIcon);
        logoLabel.setHorizontalAlignment(JLabel.CENTER); // Centraliza a imagem

        // Se você quiser adicionar a imagem a um JPanel já existente no formulário (por exemplo, jPanelLogo)
        txtLogo.setLayout(new BorderLayout()); // Certifique-se de usar o layout correto
        txtLogo.add(logoLabel, BorderLayout.CENTER); // Adiciona o JLabel ao painel

        // Revalida e repinta para garantir que o layout seja atualizado
        //txtLogo.revalidate();
        //txtLogo.repaint();
        this.setLocationRelativeTo(null);
    }

    public JMenu getMnuBuscar() {
        return mnuBuscar;
    }


    public JMenu getMnuCadastrar() {
        return mnuCadastrar;
    }

    public JMenu getMnuEntrada() {
        return mnuEntrada;
    }

    public JMenu getMnuRelatorios() {
        return mnuRelatorios;
    }

    public JMenu getMnuSaida() {
        return mnuSaida;
    }

    public JButton getBtnCliente() {
        return btnCliente;
    }

    public JButton getBtnEntrada() {
        return btnEntrada;
    }

    public JButton getBtnEntregador() {
        return btnEntregador;
    }

    public JButton getBtnSaida() {
        return btnSaida;
    }

    public JButton getBtnStatus() {
        return btnStatus;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public JButton getBtnRelatorioEntrada() {
        return btnRelatorioEntrada;
    }

    public JButton getBtnRelatorioEntrega() {
        return btnRelatorioEntrega;
    }

    public JButton getBtnRelatorioSaida() {
        return btnRelatorioSaida;
    }

    public JLabel getTxtBD() {
        return txtBD;
    }

    




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cxtBuscar = new javax.swing.JTextField();
        txtNome = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnEntregador = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        txtCadastros = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSaida = new javax.swing.JButton();
        btnEntrada = new javax.swing.JButton();
        btnStatus = new javax.swing.JButton();
        txtEntradaSaida = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JLabel();
        txtLogo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtRelatorio = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnRelatorioSaida = new javax.swing.JButton();
        btnRelatorioEntrega = new javax.swing.JButton();
        btnRelatorioEntrada = new javax.swing.JButton();
        txtDev = new javax.swing.JLabel();
        txtBD = new javax.swing.JLabel();
        txtVersao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastrar = new javax.swing.JMenu();
        mnuCadCliente = new javax.swing.JMenuItem();
        sprCadastro = new javax.swing.JPopupMenu.Separator();
        mnuCadEntregador = new javax.swing.JMenuItem();
        mnuBuscar = new javax.swing.JMenu();
        mniBuscaPorCPF = new javax.swing.JMenuItem();
        mnuEntrada = new javax.swing.JMenu();
        mniEntradaPacote = new javax.swing.JMenuItem();
        mnuSaida = new javax.swing.JMenu();
        mniSaidaPacote = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        mniRelatorioEntrada = new javax.swing.JMenuItem();
        mniRelatorioEntrega = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxtBuscarActionPerformed(evt);
            }
        });

        txtNome.setText("Nome");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/database_search.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnEntregador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/24x24/user_add.png"))); // NOI18N
        btnEntregador.setText("Cadastrar Entregador");
        btnEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadEntregadorActionPerformed(evt);
            }
        });

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/24x24/user_add.png"))); // NOI18N
        btnCliente.setText(" Cadastrar Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEntregador, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        txtCadastros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCadastros.setForeground(new java.awt.Color(204, 204, 204));
        txtCadastros.setText("Cadastros ");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/24x24/down.png"))); // NOI18N
        btnSaida.setText("   Nova Saída");
        btnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSaidaPacoteActionPerformed(evt);
            }
        });

        btnEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/24x24/up.png"))); // NOI18N
        btnEntrada.setText("Nova Entrada");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEntradaPacoteActionPerformed(evt);
            }
        });

        btnStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/24x24/info.png"))); // NOI18N
        btnStatus.setText("Status Entrega");
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusmniSaidaPacoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        txtEntradaSaida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEntradaSaida.setForeground(new java.awt.Color(204, 204, 204));
        txtEntradaSaida.setText("Entrada/Saída");

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscar.setText("Buscar");

        txtRelatorio.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtRelatorio.setForeground(new java.awt.Color(204, 204, 204));
        txtRelatorio.setText("Relatórios");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnRelatorioSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/24x24/database_down.png"))); // NOI18N
        btnRelatorioSaida.setText("Relatório de  Saídas");
        btnRelatorioSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioSaidaActionPerformed(evt);
            }
        });

        btnRelatorioEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/24x24/home_next.png"))); // NOI18N
        btnRelatorioEntrega.setText("Relatório de Entregas");
        btnRelatorioEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioEntregaActionPerformed(evt);
            }
        });

        btnRelatorioEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/24x24/database_up.png"))); // NOI18N
        btnRelatorioEntrada.setText("Relatório Entradas");
        btnRelatorioEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRelatorioSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRelatorioEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(btnRelatorioEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnRelatorioEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRelatorioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnRelatorioSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        txtDev.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtDev.setText("Desenvolvido por : Paulo Henrique Freitas");

        txtBD.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtBD.setText("Banco de Dados");

        txtVersao.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtVersao.setText("Versão: 0.1 Beta");

        mnuCadastrar.setText("Cadastrar");

        mnuCadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/user_add.png"))); // NOI18N
        mnuCadCliente.setText("Cadastrar cliente");
        mnuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadClienteActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadCliente);
        mnuCadastrar.add(sprCadastro);

        mnuCadEntregador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuCadEntregador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/user_add.png"))); // NOI18N
        mnuCadEntregador.setText("Cadastrar entregador");
        mnuCadEntregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadEntregadorActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadEntregador);

        jMenuBar1.add(mnuCadastrar);

        mnuBuscar.setText("Buscar");

        mniBuscaPorCPF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniBuscaPorCPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/search.png"))); // NOI18N
        mniBuscaPorCPF.setText("Buscar encomenda");
        mniBuscaPorCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBuscaPorCPFActionPerformed(evt);
            }
        });
        mnuBuscar.add(mniBuscaPorCPF);

        jMenuBar1.add(mnuBuscar);

        mnuEntrada.setText("Entrada");

        mniEntradaPacote.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        mniEntradaPacote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/add.png"))); // NOI18N
        mniEntradaPacote.setText("Nova entrada de pacote");
        mniEntradaPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEntradaPacoteActionPerformed(evt);
            }
        });
        mnuEntrada.add(mniEntradaPacote);

        jMenuBar1.add(mnuEntrada);

        mnuSaida.setText("Saida");

        mniSaidaPacote.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        mniSaidaPacote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/home_next.png"))); // NOI18N
        mniSaidaPacote.setText("Nova saída de pacote");
        mniSaidaPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSaidaPacoteActionPerformed(evt);
            }
        });
        mnuSaida.add(mniSaidaPacote);

        jMenuBar1.add(mnuSaida);

        mnuRelatorios.setText("Relatorios");

        mniRelatorioEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/home_next.png"))); // NOI18N
        mniRelatorioEntrada.setText("Relatório de Entradas");
        mnuRelatorios.add(mniRelatorioEntrada);

        mniRelatorioEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/database_up.png"))); // NOI18N
        mniRelatorioEntrega.setText("Relatório de Entregas");
        mnuRelatorios.add(mniRelatorioEntrega);

        jMenuBar1.add(mnuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(txtCadastros)
                .addGap(143, 143, 143)
                .addComponent(txtEntradaSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtRelatorio)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtVersao)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDev)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                                .addComponent(txtBD))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNome)
                                .addGap(18, 18, 18)
                                .addComponent(cxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(txtBuscar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtBuscar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNome))
                            .addComponent(btnBuscar))
                        .addGap(29, 29, 29)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEntradaSaida)
                            .addComponent(txtRelatorio)
                            .addComponent(txtCadastros))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDev)
                    .addComponent(txtBD)
                    .addComponent(txtVersao))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniBuscaPorCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBuscaPorCPFActionPerformed
        GerenciadorInterface.getMyInstance().abrirBuscarEncomenda();
    }//GEN-LAST:event_mniBuscaPorCPFActionPerformed

    private void mnuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadClienteActionPerformed
        GerenciadorInterface.getMyInstance().abrirCadastroCliente();
    }//GEN-LAST:event_mnuCadClienteActionPerformed

    private void mniEntradaPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEntradaPacoteActionPerformed

        //DlgEntrada janelaEntrada = new DlgEntrada(this, true);
        //janelaEntrada.setVisible(true);
        GerenciadorInterface.getMyInstance().abrirNovaEntrada();
    }//GEN-LAST:event_mniEntradaPacoteActionPerformed

    private void mniSaidaPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSaidaPacoteActionPerformed

        //DlgSaida janelaSaida = new DlgSaida(this, true);
        //janelaSaida.setVisible(true);
        GerenciadorInterface.getMyInstance().abrirNovaSaida();
    }//GEN-LAST:event_mniSaidaPacoteActionPerformed

    private void mnuCadEntregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadEntregadorActionPerformed
        //DlgCadEntregadores janelaEntregador = new DlgCadEntregadores(this, true);
        //janelaEntregador.setVisible(true);
        GerenciadorInterface.getMyInstance().abrirCadastroEntregadores();
    }//GEN-LAST:event_mnuCadEntregadorActionPerformed

    private void cxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String nome = "";
        if (validarCampos()) {
            nome = cxtBuscar.getText();
            GerenciadorInterface.getMyInstance().abrirBuscarEncomenda();
        } else {
            JOptionPane.showMessageDialog(this, "Digite o Cliente que Deseja Buscar", "Erro na Busca", JOptionPane.ERROR_MESSAGE);

        }

        cxtBuscar.setText("");
        

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRelatorioEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioEntregaActionPerformed
        // TODO add your handling code here:
        GerenciadorInterface.getMyInstance().abrirRelatorioEntregas();
    }//GEN-LAST:event_btnRelatorioEntregaActionPerformed

    private void btnStatusmniSaidaPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusmniSaidaPacoteActionPerformed
        // TODO add your handling code here:
        GerenciadorInterface.getMyInstance().abrirStatus();
    }//GEN-LAST:event_btnStatusmniSaidaPacoteActionPerformed

    private void btnRelatorioSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioSaidaActionPerformed
        // TODO add your handling code here:
        GerenciadorInterface.getMyInstance().abrirRelatorioSaidas();
    }//GEN-LAST:event_btnRelatorioSaidaActionPerformed

    private void btnRelatorioEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioEntradaActionPerformed
        // TODO add your handling code here:
        GerenciadorInterface.getMyInstance().abrirRelatorioEntradas();
    }//GEN-LAST:event_btnRelatorioEntradaActionPerformed

    public String getCxtBuscar() {
        return cxtBuscar.getText().toString();
    }

    public void setCxtBuscar(JTextField cxtBuscar) {
        this.cxtBuscar = cxtBuscar;
    }
    private boolean validarCampos() {
        //String msgErro = "";
        int invalidos = 0;

        if (cxtBuscar.getText().trim().isEmpty()) {
            //msgErro = msgErro + "Digite seu nome.\n";
            invalidos++;

        }
        if (invalidos == 0) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnEntregador;
    private javax.swing.JButton btnRelatorioEntrada;
    private javax.swing.JButton btnRelatorioEntrega;
    private javax.swing.JButton btnRelatorioSaida;
    private javax.swing.JButton btnSaida;
    private javax.swing.JButton btnStatus;
    private javax.swing.JTextField cxtBuscar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem mniBuscaPorCPF;
    private javax.swing.JMenuItem mniEntradaPacote;
    private javax.swing.JMenuItem mniRelatorioEntrada;
    private javax.swing.JMenuItem mniRelatorioEntrega;
    private javax.swing.JMenuItem mniSaidaPacote;
    private javax.swing.JMenu mnuBuscar;
    private javax.swing.JMenuItem mnuCadCliente;
    private javax.swing.JMenuItem mnuCadEntregador;
    private javax.swing.JMenu mnuCadastrar;
    private javax.swing.JMenu mnuEntrada;
    private javax.swing.JMenu mnuRelatorios;
    private javax.swing.JMenu mnuSaida;
    private javax.swing.JPopupMenu.Separator sprCadastro;
    private javax.swing.JLabel txtBD;
    private javax.swing.JLabel txtBuscar;
    private javax.swing.JLabel txtCadastros;
    private javax.swing.JLabel txtDev;
    private javax.swing.JLabel txtEntradaSaida;
    private javax.swing.JLabel txtLogo;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtRelatorio;
    private javax.swing.JLabel txtVersao;
    // End of variables declaration//GEN-END:variables
}
